version: "3.8"

services:
  postgres:
    container_name: api-solid-postgres
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-solid
    volumes:
      - ./data/pg:/bitnami/postgresql
